// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjvsXGcni8tDL3YrTVXoMaX1Lc0ykndlE',
    appId: '1:712430908933:web:8f58e5b433ac4df3168e6c',
    messagingSenderId: '712430908933',
    projectId: 'pet-backend-d2b1f',
    authDomain: 'pet-backend-d2b1f.firebaseapp.com',
    storageBucket: 'pet-backend-d2b1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA400IR8w8RRCreaeejt2IF2a4_mrrzjDY',
    appId: '1:712430908933:android:497e32d3dadae8a3168e6c',
    messagingSenderId: '712430908933',
    projectId: 'pet-backend-d2b1f',
    storageBucket: 'pet-backend-d2b1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvRFQLx8ViexOOY2gJx8infJ7raNS0Ucw',
    appId: '1:712430908933:ios:96923e8f5170293e168e6c',
    messagingSenderId: '712430908933',
    projectId: 'pet-backend-d2b1f',
    storageBucket: 'pet-backend-d2b1f.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvRFQLx8ViexOOY2gJx8infJ7raNS0Ucw',
    appId: '1:712430908933:ios:96923e8f5170293e168e6c',
    messagingSenderId: '712430908933',
    projectId: 'pet-backend-d2b1f',
    storageBucket: 'pet-backend-d2b1f.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjvsXGcni8tDL3YrTVXoMaX1Lc0ykndlE',
    appId: '1:712430908933:web:020b5a2635bfed06168e6c',
    messagingSenderId: '712430908933',
    projectId: 'pet-backend-d2b1f',
    authDomain: 'pet-backend-d2b1f.firebaseapp.com',
    storageBucket: 'pet-backend-d2b1f.firebasestorage.app',
  );
}
